bin/normalizeEnv.js
https://github.com/interledgerjs/ilp-kit-cli/pull/26 puts the variable `ILP_KIT_CLI_VERSION` into env.list. When ILP Kit CLI is updated or patched, the ILP Kit should be changed so that the `ILP_KIT_SUPPORTED_VERSION` variable in `bin/normalizeEnv` doesn't support anything older.
=> Feat: check ILP_KIT_CLI_VERSION in env.list

bin/normalizeEnv.js
From now on, the `ilp-kit-cli`'s semantic version will follow the `env.list` format. An update to the `ilp-kit-cli` will be a major version iff it breaks the `env.list` format.
=> Fix: expect ilp-kit-cli version to follow semver for env.list format

api/src/controllers/peers.js, api/src/controllers/webfinger.js, api/src/lib/connector.js, api/src/lib/utils.js, api/src/migrations/20170110-peers.js, api/src/models/peer.js, package.json, src/containers/PeerAddForm/PeerAddForm.js
@sharafian here's the proposed rpc handler.
`plugin-virtual` makes a `POST` request to `options.RPCUri` (https://example.com/api/peers/rpc) adding a `method` query param and the json body.
```
POST https://example.com/api/peers/rpc?method=send_transfer
{
"id": "3a2a1d9e-8640-4d2d-b06c-84f2cd613204",
"ledger": "us.usd.interledger.",
"account": "us.usd.interledger.other",
"amount": "5.0",
"data": {
"field": "some stuff"
},
"executionCondition": "8ZdpKBDUV-KX_OnFZTsCWB_5mlCFI3DynX5f5H2dN-Y",
"expiresAt": "2016-10-25T08:41:59.795Z"
}
```
=> feat: add peer rpc handler

api/src/controllers/peers.js, api/src/lib/connector.js
Return a 404 when the plugin with the given prefix isn't found, and return a 422 when the `receive` function on the plugin gives an error. The 404 message is printed with the `debug` log level, so that  you won't see unreciprocated peers by default.
=> Fix: better errors on plugin RPC

README.md
It wasn't clear to me where the setup instructions were, I ended up following an outdated gist because I didn't realize the headers and ToC-entries in the readme were actually hyperlinks :)
=> More explicit links to docs in readme

api/test/utils.test.js, package.json
The cause of #204 was fixed upstream in webfinger.js; this PR updates the dependency and adds a unit test for the bug.
=> Upgrade to webfinger.js version 2.6.1, fix #204

Aptfile, Procfile, README.md, app.json
Adds the button to the README page, and makes it easy to deploy ILP Kit versions.
What can be improved for a dev's life in Heroku:
1. Easy way to configure Environment variables
2. Automatic Deploy (If anyone pushes to `master`, it gets automatically deployed)*
3. Free SSL, and no need to buy a domain
4. ITS FREE! 😃  (And can be scalable/increase computing power if needed)
*Requires setup in the Heroku. Go to "Deploy", login with Github, and setup autodeploy.
=> Add deploy-to-heroku button

api/src/lib/utils.js, api/test/utils.test.js, package.json
This allows us to reenable a number of tests for `api/src/utils.js`
=> Upgrade to webfinger.js v2.6.2

api/test/utils.test.js
You updated the webfinger behavior, but not the fixture for it in the api tests. This patch adds the corresponding fixture change.
=> Fix `npm run test-api` in 2.0 branch

circle.yml
It was creating a Docker tag based on `git describe --tags` and then trying to push the one based on `git describe`. That is sometimes the same but not always, so safer to use the `git describe --tags` in both cases. This will hopefully make master green again.
=> build: Align pushed Docker tag with the one that was created

CHANGELOG.md, docs/UPGRADE.md, package.json
I manually tested this version on ilp-kit.michielbdejong.com, and found it works, at least on my machine: I was able to send money to Dennis's, Ivan's, and John's ilp-kits, all of which run v1.2.0 according to https://connector.land.
I couldn't send money to Ben's or Evan's ilp-kit, but they are both on v1.1.0, so maybe they also haven't been restarted for a long time?
@sharafian @emschwartz it would be interesting to see if I can send to your ilp-kits after you restart them.
This PR also includes upgrade instructions, especially the hint to check `/api/health` and restart the api process if necessary, which helps avoid the "Cannot access object.githubAuth of null" errors on the login page.
=> Tag v1.2.1

api/src/lib/utils.js, api/test/utils.test.js
This uses fixtures from the spsp spec, and checks that the api call returns an appropriate currencySymbol for a well-known currency.
=> Fix spsp test fixtures

api/src/controllers/peers.js, api/src/lib/config.js, api/src/lib/connector.js, package.json
Uses `.authorize` on plugin virtual to authenticate RPC requests. The plugin uses a symmetric token (an HMAC of the shared secret) to authenticate RPC requests. Depends on https://github.com/interledgerjs/ilp-plugin-virtual/pull/58
=> Feat: BREAKING take authorization for RPC requests

Dockerfile, api/src/controllers/auth.js, api/src/lib/spsp.js, api/src/lib/utils.js, src/containers/Settings/ProfileForm.js
1. The dockerfile wasn't rebuilding dependencies, so if you ran `docker build` on a system that didn't match the one in `node:7-slim` it would fail to load any native modules. (Unfortunately this means the docker image needs build tools inside)
2. The webfinger call is taken out for local transfers, because we already know our own SPSP endpoint. This makes loading a little quicker, and also means that we don't need HTTPS so long as we're just sending within our own ILP Kit (so long as HTTPS was disabled on the ILP kit).
3. The profile picture code broke at some point, so this fixes it by using the correct file extension for the cropped output file
=> Fix: Dockerfile, local webfinger calls, and profile picture cropping

Dockerfile
Missing libpq causes ILP Kit to crash when being run from the docker image. Whoever approves can merge this PR.
=> Fix: add libpq5 to docker image

api/src/lib/pay.js
If the user hasn't set a name, then their identifier (eg. `user@host.example`) should be used instead. Closes https://github.com/interledgerjs/ilp-kit/issues/342
=> Feat: fallback to source identifier if user has no name

package.json, scripts/postgres_version_check.sh
Adds error throw logic during `npm run configure` if psql version is behind v9.5.
Solves issue #311.
=> Scan system to check if Postgres version is up to date

package.json
Loads the published version of koa-socket-2 instead of a specific github commit.
=> build: Changes from where dependency koa-socket-2 is loaded

package.json
ilp-connector@21.0.1 supports liquidity curve quotes, and should fix the integration tests.
=> chore: ilp-connector@21.0.1

src/containers/Peers/Peers.js
@vhpoet any idea why this was set to http (not https)?
=> on Peers tab, link to https url, not http

api/src/lib/app.js, api/src/lib/connector.js, package.json
* Fixes https://github.com/interledgerjs/ilp-kit/issues/430
* Fixes intermittent five-bells-integration-test failures.
* Requires [ilp-connector@21.1.6](https://github.com/interledgerjs/ilp-connector/issues/356).
Right now `connector.listen()` won't return until all ledgers are connected (see [ilp-connector/app.js](https://github.com/interledgerjs/ilp-connector/blob/0c5fad9a3b0317bbd3bdb04aef13f978d1ff9b96/src/app.js#L50-L51)), which could cause delays starting ilp-kit as well. Should it just return after the first attempt, and handle the retries in the background?
=> fix: ensure connector ready before start() returns

Dockerfile, circle.yml, package.json
Fixes https://github.com/interledgerjs/ilp-kit/issues/458
Also, disable all integration tests _except_ the ilp-kit ones.
=> chore: try node 8 in circleci with connector fix
