- .gitignore
- circle.yml
- package.json
- scripts/publish_spec.sh
- scripts/publish_web.js
Changes to the API documentation on interledger.org.
> Automatically publish gh-pages

- api/test/auth.test.js
- api/test/health.test.js
- api/test/helpers/app.js
- api/test/users.test.js
- api/test/webfinger.test.js
- package.json
adds a couple ticks of delay to stop database from inconsistently failing during the API tests
> Test: fix inconsistent errors

- docs/SETUP.md
As per https://github.com/interledgerjs/ilp-kit/issues/106
> Docs: update setup

- docs/DEV.md
I had to do these steps when I was setting up a dev environment, so we should add them to the dev instructions.
> Docs: document modules and websockets in DEV

- docs/DEV.md
A required module was missing and a link was broken.
> chore: fix dev instructions

- api/src/lib/app.js
Just try to create the uploads folder, instead of checking if it exists. It's easier to ask forgiveness than it is to get permission.
> fix: Fixes #182 (upload folder race condition)

- bin/normalizeEnv.js
Resubmit of https://github.com/interledgerjs/ilp-kit/pull/220
> fix: allow version to be passed to cli and bypass file

- docs/SETUP.md
closes https://github.com/interledgerjs/ilp-kit/issues/222
> docs: mention postgres version

- api/src/controllers/users.js
- api/src/lib/antifraud.js
- api/src/lib/ledger.js
- api/src/migrations/20170308-user_invite_fk.js
- api/src/models/user.js
- Changes the logic used to create accounts to use transactions
- Ensures that invite codes can only be claimed once
Depends on interledgerjs/five-bells-service-manager#20 and tested by interledgerjs/five-bells-integration-test#66.
> fix: use transactions to create users

- circle.yml
Attempt to trigger a build using https://github.com/interledgerjs/five-bells-service-manager/pull/25
> Fix event handler

- api/src/controllers/peers.js
- api/src/lib/config.js
- api/src/lib/connector.js
Rebase of @sharafian's https://github.com/interledgerjs/ilp-kit/pull/291
It was previously lost in a rebase (my fault, sorry!)
> feat: take authorization for RPC requests

- package.json
- pm2.config.js
- src/containers/PeerAddForm/PeerAddForm.js
- src/redux/reducer.js
> docs: fix node execution dir for web service in pm2 config

- api/src/lib/pay.js
- api/src/lib/spsp.js
- api/src/lib/utils.js
Closes https://github.com/interledgerjs/ilp-kit/issues/327 .
> Fix: show names and images for incoming and outgoing payments

- api/src/controllers/users.js
- src/containers/Users/Users.js
Closes https://github.com/interledgerjs/ilp-kit/issues/307 .
> Fix: add balances to the users page again

- api/src/lib/connector.js
Closes https://github.com/interledgerjs/ilp-kit/issues/232 .
> Fix: remove plugins that gave errors on addPlugin

- src/containers/SendForm/SendValidation.js
- src/utils/validation.js
Closes https://github.com/interledgerjs/ilp-kit/issues/219 . Also gives an error message that includes your minimum allowed balance.
> Fix: compare to min balance instead of balance when sending

- docs/UPGRADE.md
- package.json
Companion to https://github.com/interledgerjs/ilp-routing/pull/40
> Use route notes and quote in ledger units

- api/src/lib/app.js
> fix: fixes initial connector funding

- src/containers/Peers/Peers.js
Closes https://github.com/interledgerjs/ilp-kit/issues/364 .
> Fix: call PUT peer correctly when adjusting limit

- yarn.lock
Bring the yarn file a bit closer to what we're testing in the integration tests. We should really do this as part of each release.
> feat: newer yarn lock

- api/src/lib/utils.js
Turns out circleci didn't run on #407, this should fix the unit tests.
> fix: self->this in #407

- api/package.json
- api/src/controllers/payments.js
- api/src/controllers/peers.js
- api/src/errors/insufficient-liquidity-error.js
- api/src/lib/connector.js
- client/src/containers/SendForm/SendForm.js
- docs/apache.md
* display Insufficient Liquidity errors (Fixes #400)
* display trustline balance after unpeer (Fixes #462)
* display peer online status correctly (Fixes #465)
* update apache setup instructions
> misc. v4 fixes

- api/src/lib/app.js
- api/src/lib/connector.js
- circle.yml
- client/scripts/client.js
- install-all.sh
- package.json
- start-all.sh
Depends on https://github.com/interledgerjs/five-bells-service-manager/pull/34 and https://github.com/interledgerjs/five-bells-integration-test/pull/87
Fixes https://github.com/interledgerjs/ilp-kit/issues/471
> fix integration tests

- Dockerfile
- api/package.json
- package.json
- start-all.sh
- webserver/webserver.js
Trying to get v4 working in Docker.
> Docker fixes
